"""
ESE5880C Project 2 — Effluent Data Analysis
==============================================
Author: (Your Name)
Date: 2026-03-21

Task: Analyze BioWin simulation outputs to study the effect of influent autocorrelation
(r = 0, 0.3, 0.6, 0.9) on effluent quality (COD, TSS) and sludge production.

Outputs are saved to:  output/figures/   (PNG plots, 300 DPI)
                       output/summary.md  (written analysis report)
"""

import os, sys, re, zipfile, csv, io, time
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D
from scipy import stats

# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NOSELF_DIR  = os.path.join(BASE, "data", "biowin", "biowin data NO self-related")
SELF_DIR    = os.path.join(BASE, "data", "biowin", "biowin data self-related")
OUTPUT_DIR  = os.path.join(BASE, "output")
FIG_DIR     = os.path.join(OUTPUT_DIR, "figures")
CACHE_DIR   = os.path.join(OUTPUT_DIR, "cache")

os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(CACHE_DIR, exist_ok=True)

# Discharge standards (China Class 1A, GB18918-2002)
COD_STANDARD = 60.0   # mg/L
TSS_STANDARD = 30.0   # mg/L

# Plot style
COLORS = {0: '#555555', 0.3: '#4575b4', 0.6: '#f46d43', 0.9: '#d73027'}
COLOR_CV = {'small': '#1a9850', 'typical': '#4575b4', 'large': '#d73027'}
ALPHA = 0.75
DPI = 300

plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'axes.titlesize': 13,
    'axes.labelsize': 11,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'legend.fontsize': 9,
    'figure.facecolor': 'white',
    'axes.facecolor': '#f8f8f8',
    'axes.grid': True,
    'grid.color': 'white',
    'grid.linewidth': 1.0,
})


# ─────────────────────────────────────────────
# CSV-BASED DATA LOADER  (fast — CSVs pre-generated by convert_xlsx.py)
# ─────────────────────────────────────────────

# Map header name → internal key
NAME_MAP = {
    'Time (days)':                              'time',
    'Time (days)_(365days)':                    'time',
    'Influent - COD0 BOD - Total Carbonaceous': 'inf_bod',
    'Influent - COD0 COD - Total':              'inf_cod',
    'Bioreactor1 Total suspended solids':       'bio_tss',
    'Bioreactor1 Volatile suspended solids':    'bio_vss',
    'Bioreactor1 OUR - Carbonaceous':           'bio_our_c',
    'Bioreactor1 Element HRT':                  'bio_hrt',
    'Bioreactor1 OUR - Total':                  'bio_our_t',
    'Effluent3 BOD - Total Carbonaceous':       'eff_bod',
    'Effluent3 Total suspended solids':         'eff_tss',
    'Effluent3 COD - Filtered':                 'eff_cod',
    'Effluent3 Flow':                           'eff_flow',
    'Sludge8 BOD - Total Carbonaceous':         'slu_bod',
    'Sludge8 COD - Total':                      'slu_cod',
    'Sludge8 Total suspended solids':           'slu_tss',
    'Sludge8 Volatile suspended solids':        'slu_vss',
    'Sludge8 Flow':                             'slu_flow',
}

# CSV filename map: dataset key → csv filename in CACHE_DIR
CSV_MAP = {
    ('typical', 0):    'noself_typical_r0.csv',
    ('small',   0):    'noself_small_r0.csv',
    ('large',   0):    'noself_large_r0.csv',
    ('typical', 0.3):  'self_typical_r0_3.csv',
    ('typical', 0.6):  'self_typical_r0_6.csv',
    ('typical', 0.9):  'self_typical_r0_9.csv',
    ('small',   0.3):  'self_small_r0_3.csv',
    ('small',   0.6):  'self_small_r0_6.csv',
    ('small',   0.9):  'self_small_r0_9.csv',
    ('large',   0.3):  'self_large_r0_3.csv',
    ('large',   0.6):  'self_large_r0_6.csv',
    ('large',   0.9):  'self_large_r0_9.csv',
}


def load_csv(csv_path):
    """Load a BioWin CSV (pre-converted from xlsx) into a dict of numpy arrays."""
    import csv as csvmod
    print(f"  [load] {os.path.basename(csv_path)}")
    t0 = time.time()
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csvmod.reader(f)
        header_row = next(reader)
        headers = [h.strip().strip('"') for h in header_row]
        # Map headers to internal keys
        col_keys = [NAME_MAP.get(h, None) for h in headers]
        # Collect data per column
        col_data = [[] for _ in headers]
        for row in reader:
            for i, val in enumerate(row):
                if i < len(col_data):
                    try:
                        col_data[i].append(float(val))
                    except (ValueError, TypeError):
                        col_data[i].append(np.nan)
    result = {}
    for key, vals in zip(col_keys, col_data):
        if key is not None:
            result[key] = np.array(vals, dtype=float)
    print(f"  [done] {os.path.basename(csv_path)} in {time.time()-t0:.1f}s  "
          f"(n={len(next(iter(result.values()), []))})")
    return result


def load_all_datasets():
    """Return a dict of all relevant BioWin datasets, loading from CSV cache."""
    print("\n=== Loading datasets ===")
    ds = {}
    for ds_key, csv_name in CSV_MAP.items():
        csv_path = os.path.join(CACHE_DIR, csv_name)
        if not os.path.exists(csv_path):
            print(f"  [skip] {csv_name} not found — run convert_xlsx.py first")
            continue
        try:
            ds[ds_key] = load_csv(csv_path)
        except Exception as e:
            print(f"  [err]  {csv_name}: {e}")
    print("=== All datasets loaded ===\n")
    return ds




def _parse_xlsx_to_arrays(xlsx_path, sheet_index=0):
    """Parse xlsx using streaming iterparse — fast even for 20MB XML files."""
    import xml.etree.ElementTree as ET

    NS = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'

    with zipfile.ZipFile(xlsx_path, 'r') as z:
        names = z.namelist()

        # ── Shared strings (small file, load fully) ──────────────────────
        shared = []
        if 'xl/sharedStrings.xml' in names:
            ss_data = z.read('xl/sharedStrings.xml')
            ss_root = ET.fromstring(ss_data)
            for si in ss_root.findall(f'{{{NS}}}si'):
                t = si.find(f'{{{NS}}}t')
                if t is not None and t.text:
                    shared.append(t.text)
                else:
                    # Concatenate all <t> children
                    texts = [t2.text or '' for t2 in si.findall(f'.//{{{NS}}}t')]
                    shared.append(''.join(texts))

        # ── Pick correct worksheet ─────────────────────────────────────
        sheet_files = sorted(
            [n for n in names if re.match(r'xl/worksheets/sheet\d+\.xml', n)],
            key=lambda x: int(re.search(r'sheet(\d+)', x).group(1))
        )
        if sheet_index >= len(sheet_files):
            sheet_index = 0
        target = sheet_files[sheet_index]

        # ── Stream-parse the (large) worksheet ───────────────────────────
        header_map = {}   # col_letter -> header name
        col_arrays  = {}  # col_letter -> list of floats
        current_row = None
        current_col = None
        current_type = None
        current_val  = None

        with z.open(target) as fh:
            for event, elem in ET.iterparse(fh, events=('start', 'end')):
                tag = elem.tag.split('}', 1)[-1] if '}' in elem.tag else elem.tag

                if event == 'start' and tag == 'row':
                    current_row = int(elem.get('r', '0'))

                elif event == 'start' and tag == 'c':
                    ref = elem.get('r', '')
                    # Extract column letter
                    current_col = ''.join(ch for ch in ref if ch.isalpha())
                    current_type = elem.get('t', '')
                    current_val  = None

                elif event == 'end' and tag == 'v':
                    current_val = elem.text

                elif event == 'end' and tag == 'c':
                    if current_val is None:
                        current_col = None
                        current_type = None
                        continue
                    if current_row == 1:
                        if current_type == 's':
                            idx = int(current_val)
                            header_map[current_col] = shared[idx] if idx < len(shared) else current_val
                    else:
                        if current_type != 's':  # skip string data cells
                            try:
                                fval = float(current_val)
                                col_arrays.setdefault(current_col, []).append(fval)
                            except (ValueError, TypeError):
                                pass
                    current_col = None
                    current_type = None
                    current_val  = None

                # Free memory — critical for large files
                if event == 'end' and tag == 'row':
                    elem.clear()

    if not header_map:
        raise ValueError(f"No header row found in {xlsx_path} sheet{sheet_index}")

    # Convert lists → numpy arrays; pad missing values with NaN
    max_len = max((len(v) for v in col_arrays.values()), default=0)
    result = {'_headers': header_map}
    for cl, vals in col_arrays.items():
        arr = np.full(max_len, np.nan)
        arr[:len(vals)] = vals
        result[cl] = arr

    return result


def _cache_path(xlsx_path, sheet_index):
    base = os.path.basename(xlsx_path).replace('.xlsx','')
    return os.path.join(CACHE_DIR, f"{base}_sheet{sheet_index}.npz")


def load_biowin(xlsx_path, sheet_index=0, force_reload=False):
    """Load BioWin xlsx output. Caches as npz for fast repeated access."""
    cache = _cache_path(xlsx_path, sheet_index)
    if os.path.exists(cache) and not force_reload:
        print(f"  [cache] {os.path.basename(xlsx_path)} sheet{sheet_index}")
        npz = np.load(cache, allow_pickle=True)
        return {k: npz[k] for k in npz.files}

    print(f"  [parse] {os.path.basename(xlsx_path)} sheet{sheet_index} ...")
    t0 = time.time()
    raw = _parse_xlsx_to_arrays(xlsx_path, sheet_index)
    headers = raw['_headers']

    # Build standardized dict by looking up known column names
    # Map header string → key
    NAME_MAP = {
        'Time (days)':                             'time',
        'Time (days)_(365days)':                   'time',
        'Influent - COD0 BOD - Total Carbonaceous':'inf_bod',
        'Influent - COD0 COD - Total':             'inf_cod',
        'Bioreactor1 Total suspended solids':      'bio_tss',
        'Bioreactor1 Volatile suspended solids':   'bio_vss',
        'Bioreactor1 OUR - Carbonaceous':          'bio_our_c',
        'Bioreactor1 Element HRT':                 'bio_hrt',
        'Bioreactor1 OUR - Total':                 'bio_our_t',
        'Effluent3 BOD - Total Carbonaceous':      'eff_bod',
        'Effluent3 Total suspended solids':        'eff_tss',
        'Effluent3 COD - Filtered':                'eff_cod',
        'Effluent3 Flow':                          'eff_flow',
        'Sludge8 BOD - Total Carbonaceous':        'slu_bod',
        'Sludge8 COD - Total':                     'slu_cod',
        'Sludge8 Total suspended solids':          'slu_tss',
        'Sludge8 Volatile suspended solids':       'slu_vss',
        'Sludge8 Flow':                            'slu_flow',
    }

    data = {}
    for col_l, hdr in headers.items():
        key = NAME_MAP.get(hdr)
        if key and col_l in raw:
            data[key] = raw[col_l]

    if 'time' not in data:
        # Use first numeric array as time
        for col_l in sorted(raw.keys()):
            if col_l != '_headers':
                data.setdefault('time', raw[col_l])
                break

    np.savez_compressed(cache, **data)
    print(f"  [done]  {os.path.basename(xlsx_path)} sheet{sheet_index} in {time.time()-t0:.1f}s")
    return data


# ─────────────────────────────────────────────
# HELPER UTILITIES
# ─────────────────────────────────────────────

def clean_outliers(v, key):
    """Remove obvious outliers based on data type."""
    if len(v) == 0:
        return v
    if key in ['slu_tss', 'slu_bod']:
        # 剩余污泥: 删除 <1000 和 >3000
        mask = (v >= 1000) & (v <= 3000)
        return v[mask]
    elif key in ['eff_cod', 'inf_cod']:
        # COD: 删除 <10 的异常值
        return v[v >= 10]
    elif key in ['eff_tss', 'bio_tss']:
        # TSS: 删除 <1 的异常值
        return v[v >= 1]
    elif key in ['eff_flow', 'slu_flow']:
        # 流量: 保持正值
        return v[v > 0]
    return v


def trim_stable(data, warmup_days=180):
    """Remove first `warmup_days` of data (warm-up period)."""
    out = {}
    t = data.get('time', np.array([]))
    if len(t) == 0:
        return data
    mask = t >= warmup_days
    for k, v in data.items():
        if isinstance(v, np.ndarray) and len(v) == len(t):
            out[k] = v[mask]
        else:
            out[k] = v
    return out


def exceedance_prob(values, threshold):
    """P(X > threshold)"""
    v = values[~np.isnan(values)]
    return np.mean(v > threshold) * 100  # percent


def acf(x, nlags=50):
    """Manual autocorrelation function."""
    x = x[~np.isnan(x)]
    n = len(x)
    x_centered = x - x.mean()
    var = np.dot(x_centered, x_centered)
    acf_vals = []
    for lag in range(nlags + 1):
        if lag == 0:
            acf_vals.append(1.0)
        else:
            cov = np.dot(x_centered[:n-lag], x_centered[lag:])
            acf_vals.append(cov / var)
    return np.array(acf_vals)


def savefig(name, fig=None):
    path = os.path.join(FIG_DIR, name)
    (fig or plt).savefig(path, dpi=DPI, bbox_inches='tight')
    plt.close('all')
    print(f"  Saved: {name}")
    return path


# ─────────────────────────────────────────────
# FIGURE 1 — INFLUENT TIME SERIES (CV comparison, r=0.6)
# ─────────────────────────────────────────────

def plot_influent_time_series(ds, days_to_show=90):
    """Fig 1: Influent COD time series for 3 CV levels (r=0.6)."""
    fig, axes = plt.subplots(2, 1, figsize=(13, 8), sharex=False)
    fig.suptitle("Influent Time Series — Effect of CV (r = 0.6)", fontsize=13, fontweight='bold')

    for ax, (key, label, ylabel) in zip(axes, [
        ('inf_cod', 'Influent COD',   'COD (mg/L)'),
        ('bio_tss', 'Bioreactor TSS',  'TSS (mg/L)'),
    ]):
        for cv, col in COLOR_CV.items():
            d = ds.get((cv, 0.6))
            if d is None:
                continue
            d = trim_stable(d)
            t = d.get('time', np.array([]))
            v = d.get(key, np.array([]))
            if len(t) == 0 or len(v) == 0:
                continue
            # Show only first `days_to_show` days of stable period
            mask = t - t[0] <= days_to_show
            ax.plot(t[mask] - t[0], v[mask], color=col, alpha=ALPHA, linewidth=1.2,  # 加粗线条
                    label=f"CV {cv}")
        ax.set_xlabel("Time (days, after warm-up)")
        ax.set_ylabel(ylabel)
        ax.set_title(label)
        ax.legend(loc='upper right', ncol=3, framealpha=0.9)

    fig.tight_layout()
    return savefig("fig1_influent_timeseries_cv.png", fig)


# ─────────────────────────────────────────────
# FIGURE 2 — INFLUENT HISTOGRAM (3 CV levels, r=0.6)
# ─────────────────────────────────────────────

def plot_influent_histogram(ds):
    """Fig 2: Histogram of influent COD/TSS for 3 CV levels."""
    fig, axes = plt.subplots(2, 3, figsize=(13, 7))
    fig.suptitle("Influent Distribution — Effect of CV (r = 0.6)", fontsize=13, fontweight='bold')
    cv_list = ['small', 'typical', 'large']
    cv_labels = ['Small CV', 'Typical CV', 'Large CV']

    for col_idx, (cv, cv_lab) in enumerate(zip(cv_list, cv_labels)):
        d = ds.get((cv, 0.6))
        if d is None:
            for row in range(2):
                axes[row, col_idx].set_title(f"{cv_lab}\n(no data)", color='gray')
            continue
        d = trim_stable(d)

        for row_idx, (key, ylabel) in enumerate([
            ('inf_cod', 'Influent COD (mg/L)'),
            ('bio_tss', 'Bioreactor TSS (mg/L)'),
        ]):
            ax = axes[row_idx, col_idx]
            v = d.get(key, np.array([]))
            v = v[~np.isnan(v)]
            if len(v) == 0:
                continue
            ax.hist(v, bins=60, color=COLOR_CV[cv], alpha=0.75, edgecolor='none', density=True)
            mu, sd = np.mean(v), np.std(v)
            # Fit normal PDF
            xs = np.linspace(v.min(), v.max(), 300)
            ax.plot(xs, stats.norm.pdf(xs, mu, sd), 'k-', lw=1.5, label='Normal fit')
            ax.axvline(mu, color='navy', lw=1, linestyle='--', label=f'μ={mu:.1f}')
            ax.set_xlabel(ylabel, fontsize=9)
            ax.set_ylabel("Density" if col_idx == 0 else "")
            ax.set_title(f"{cv_lab}\n(CV row: {['COD','TSS'][row_idx]})")
            ax.legend(fontsize=7)

    fig.tight_layout()
    return savefig("fig2_influent_histogram_cv.png", fig)


# ─────────────────────────────────────────────
# FIGURE 3 — EFFLUENT COD & TSS TIME SERIES (4 r values)
# ─────────────────────────────────────────────

def plot_effluent_time_series(ds, days_to_show=120):
    """Fig 3: Effluent COD / TSS time series for r = 0, 0.3, 0.6, 0.9."""
    r_list = [0, 0.3, 0.6, 0.9]
    fig, axes = plt.subplots(2, 1, figsize=(13, 8), sharex=False)
    fig.suptitle("Effluent Time Series — Effect of Autocorrelation (Typical CV)", fontsize=13, fontweight='bold')

    configs = [
        ('eff_cod', f'Effluent COD (mg/L)', COD_STANDARD, '60 mg/L (Std)'),
        ('eff_tss', f'Effluent TSS (mg/L)', None, None),  # TSS不显示标准线
    ]

    for ax, (key, ylabel, std_line, std_label) in zip(axes, configs):
        for r in r_list:
            d = ds.get(('typical', r))
            if d is None:
                continue
            d = trim_stable(d)
            t = d.get('time', np.array([]))
            v = d.get(key, np.array([]))
            if len(t) == 0 or len(v) == 0:
                continue

            # 数据清洗
            v_clean = clean_outliers(v, key)
            mask_clean = np.isin(v, v_clean) & (~np.isnan(v))
            t_clean = t[mask_clean]
            v_clean = v[mask_clean]

            t_rel = t_clean - t_clean[0]
            mask = t_rel <= days_to_show
            ax.plot(t_rel[mask], v_clean[mask],
                    color=COLORS[r], alpha=0.85, linewidth=1.2,  # 加粗线条
                    label=f"r = {r}")
        # Standard line - only for COD
        if std_line is not None and std_label is not None:
            ax.axhline(std_line, color='black', linewidth=1.5, linestyle='--', zorder=5,
                       label=std_label)
        ax.set_ylabel(ylabel)
        ax.set_xlabel("Time (days, after warm-up)")
        ax.legend(loc='upper right', ncol=3, framealpha=0.9)
        ax.set_title(ylabel.split('(')[0].strip())

    fig.tight_layout()
    return savefig("fig3_effluent_timeseries_r.png", fig)


# ─────────────────────────────────────────────
# FIGURE 4 — EFFLUENT HISTOGRAM (4 r values)
# ─────────────────────────────────────────────

def plot_effluent_histogram(ds):
    """Fig 4: Effluent COD/TSS histograms for 4 autocorrelation levels."""
    r_list = [0, 0.3, 0.6, 0.9]
    fig, axes = plt.subplots(2, 4, figsize=(16, 7))
    fig.suptitle("Effluent Distribution — Effect of Autocorrelation (Typical CV)", fontsize=13, fontweight='bold')

    for col_idx, r in enumerate(r_list):
        d = ds.get(('typical', r))
        if d is None:
            for row in range(2):
                axes[row, col_idx].set_title(f"r={r}\n(no data)", color='gray')
            continue
        d = trim_stable(d)

        for row_idx, (key, xlabel, std_line) in enumerate([
            ('eff_cod', 'Effluent COD (mg/L)', COD_STANDARD),
            ('eff_tss', 'Effluent TSS (mg/L)', None),  # TSS不显示标准线
        ]):
            ax = axes[row_idx, col_idx]
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            if len(v) == 0:
                continue
            ax.hist(v, bins=60, color=COLORS[r], alpha=0.75, edgecolor='none', density=True)
            mu, sd = np.mean(v), np.std(v)
            xs = np.linspace(max(0, v.min()), v.max(), 300)
            ax.plot(xs, stats.norm.pdf(xs, mu, sd), 'k-', lw=1.3)
            if std_line is not None:  # 仅对COD显示标准线
                ax.axvline(std_line, color='red', lw=1.2, linestyle='--', label='Standard')
            ax.axvline(mu, color='navy', lw=1, linestyle=':', label=f'μ={mu:.1f}')
            ax.set_title(f"r = {r}\nμ={mu:.1f}, σ={sd:.1f}")
            ax.set_xlabel(xlabel, fontsize=8)
            if col_idx == 0:
                ax.set_ylabel("Density")
            if row_idx == 0 and col_idx == 0:
                ax.legend(fontsize=7)

    fig.tight_layout()
    return savefig("fig4_effluent_histogram_r.png", fig)


# ─────────────────────────────────────────────
# FIGURE 5 — CDF / EXCEEDANCE PROBABILITY
# ─────────────────────────────────────────────

def plot_exceedance_cdf(ds):
    """Fig 5: CDF and exceedance probability for COD, TSS, Sludge TSS."""
    r_list = [0, 0.3, 0.6, 0.9]
    params = [
        ('eff_cod', 'Effluent COD (mg/L)', COD_STANDARD),
        ('eff_tss', 'Effluent TSS (mg/L)', None),  # TSS不显示标准线
        ('slu_tss', 'Sludge TSS (mg/L)',   None),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle("Exceedance Probability (CCDF) — Effect of Autocorrelation (Typical CV)",
                 fontsize=13, fontweight='bold')

    for ax, (key, xlabel, std) in zip(axes, params):
        for r in r_list:
            d = ds.get(('typical', r))
            if d is None:
                continue
            d = trim_stable(d)
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            if len(v) == 0:
                continue
            v_sorted = np.sort(v)
            ccdf = 1 - np.arange(1, len(v)+1) / len(v)
            ax.semilogy(v_sorted, ccdf * 100, color=COLORS[r], alpha=0.85,
                        linewidth=1.5, label=f"r = {r}")

        if std is not None:
            ax.axvline(std, color='black', lw=1.5, linestyle='--', label=f'Standard\n({std} mg/L)')

        ax.set_xlabel(xlabel)
        ax.set_ylabel("Exceedance Probability (%)")
        ax.set_title(xlabel.split('(')[0].strip())
        ax.legend(fontsize=8)
        ax.set_ylim(bottom=0.01)

    fig.tight_layout()
    return savefig("fig5_exceedance_cdf_r.png", fig)


# ─────────────────────────────────────────────
# FIGURE 6 — ACF PLOT (Effluent COD, 4 r values)
# ─────────────────────────────────────────────

def plot_acf(ds, nlags=72):
    """Fig 6: ACF of effluent COD and TSS for 4 autocorrelation levels."""
    r_list = [0, 0.3, 0.6, 0.9]
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle("Autocorrelation Function (ACF) of Effluent — Effect of r (Typical CV)",
                 fontsize=13, fontweight='bold')

    lags = np.arange(nlags + 1)
    # 95% confidence interval for ACF (approx ±1.96/sqrt(n))
    conf_shown = False

    for ax, (key, title) in zip(axes, [
        ('eff_cod', 'Effluent COD'),
        ('eff_tss', 'Effluent TSS'),
    ]):
        for r in r_list:
            d = ds.get(('typical', r))
            if d is None:
                continue
            d = trim_stable(d)
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            if len(v) < nlags + 2:
                continue
            a = acf(v, nlags=nlags)
            n = len(v)
            ci = 1.96 / np.sqrt(n)
            ax.plot(lags, a, color=COLORS[r], linewidth=1.5, label=f"r = {r}")
            if not conf_shown:
                ax.axhline(ci,  color='gray', linestyle='--', lw=0.8, label='95% CI')
                ax.axhline(-ci, color='gray', linestyle='--', lw=0.8)
                conf_shown = True

        ax.axhline(0, color='black', lw=0.8)
        ax.set_xlim(0, nlags)
        ax.set_ylim(-0.3, 1.05)
        ax.set_xlabel("Lag (hours)")
        ax.set_ylabel("ACF")
        ax.set_title(title)
        ax.legend(fontsize=8)

    fig.tight_layout()
    return savefig("fig6_acf_r.png", fig)


# ─────────────────────────────────────────────
# FIGURE 7 — BOX PLOT (Mean ± SD by autocorrelation)
# ─────────────────────────────────────────────

def plot_boxplot(ds):
    """Fig 7: Box plots of effluent COD/TSS for different r values."""
    r_list = [0, 0.3, 0.6, 0.9]
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    fig.suptitle("Effluent Distribution (Box Plot) — Effect of Autocorrelation (Typical CV)",
                 fontsize=13, fontweight='bold')

    for ax, (key, ylabel, std_line) in zip(axes, [
        ('eff_cod', 'Effluent COD (mg/L)', COD_STANDARD),
        ('eff_tss', 'Effluent TSS (mg/L)', None),  # TSS不显示标准线
    ]):
        data_to_plot = []
        labels = []
        for r in r_list:
            d = ds.get(('typical', r))
            if d is None:
                continue
            d = trim_stable(d)
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            data_to_plot.append(v)
            labels.append(f"r = {r}")

        bp = ax.boxplot(data_to_plot, tick_labels=labels, patch_artist=True,
                        medianprops={'color': 'black', 'linewidth': 2},
                        flierprops={'marker': '.', 'markersize': 2, 'alpha': 0.3})
        for patch, r in zip(bp['boxes'], r_list):
            patch.set_facecolor(COLORS[r])
            patch.set_alpha(0.7)

        if std_line is not None:  # 仅对COD显示标准线
            ax.axhline(std_line, color='red', lw=1.5, linestyle='--',
                       label=f'Standard ({std_line:.0f} mg/L)')
        ax.set_ylabel(ylabel)
        ax.set_title(ylabel.split('(')[0].strip())
        ax.legend(fontsize=8)

    fig.tight_layout()
    return savefig("fig7_boxplot_r.png", fig)


# ─────────────────────────────────────────────
# FIGURE 9 — SLUDGE PRODUCTION TIME SERIES & DISTRIBUTION
# ─────────────────────────────────────────────

def plot_sludge_production(ds, days_to_show=90):
    """Fig 9: Sludge TSS time series and distribution for different r levels."""
    r_list = [0, 0.3, 0.6, 0.9]
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle("Sludge Production — Effect of Autocorrelation (Typical CV)",
                 fontsize=13, fontweight='bold')

    gs = gridspec.GridSpec(2, 4, height_ratios=[1, 0.8])

    # 上面: 时间序列 (跨越4列)
    ax1 = fig.add_subplot(gs[0, :])
    has_data = False
    for r in r_list:
        d = ds.get(('typical', r))
        if d is None:
            continue
        d = trim_stable(d)
        t = d.get('time', np.array([]))
        v = d.get('slu_tss', np.array([]))
        if len(t) == 0 or len(v) == 0:
            continue

        # 数据清洗
        v_clean = clean_outliers(v, 'slu_tss')
        mask_clean = np.isin(v, v_clean) & (~np.isnan(v))
        t_clean = t[mask_clean]
        v_clean = v[mask_clean]

        t_rel = t_clean - t_clean[0]
        mask = t_rel <= days_to_show
        ax1.plot(t_rel[mask], v_clean[mask],
                 color=COLORS[r], alpha=0.85, linewidth=1.2,
                 label=f"r = {r}")
        has_data = True

    if has_data:
        ax1.set_ylabel("Sludge TSS (mg/L)")
        ax1.set_xlabel("Time (days, after warm-up)")
        ax1.set_title("Sludge TSS Time Series")
        ax1.legend(loc='upper right', ncol=4, framealpha=0.9)

    # 下面: 四个直方图 (每列一个r)
    for col_idx, r in enumerate(r_list):
        ax = fig.add_subplot(gs[1, col_idx])
        if has_data:
            d = ds.get(('typical', r))
            if d is not None:
                d = trim_stable(d)
                v = d.get('slu_tss', np.array([]))
                v = clean_outliers(v[~np.isnan(v)], 'slu_tss')
                if len(v) > 0:
                    mu, sd = np.mean(v), np.std(v)
                    ax.hist(v, bins=50, color=COLORS[r], alpha=0.7,
                            edgecolor='none', density=True)
                    ax.set_title(f"r = {r}\nμ={mu:.1f}, σ={sd:.1f}")
                    ax.set_xlabel("Sludge TSS (mg/L)", fontsize=9)
                    if col_idx == 0:
                        ax.set_ylabel("Density", fontsize=9)
                    ax.tick_params(axis='both', labelsize=8)

    fig.tight_layout()
    return savefig("fig9_sludge_production.png", fig) if has_data else None


# ─────────────────────────────────────────────
# FIGURE 8 — VIOLATION RATE TABLE PLOT
# ─────────────────────────────────────────────

def plot_violation_summary(ds):
    """Fig 8: Bar chart of exceedance probability for COD/TSS at each r level."""
    r_list = [0, 0.3, 0.6, 0.9]
    params = [
        ('eff_cod', 'COD', COD_STANDARD),
        ('eff_tss', 'TSS', TSS_STANDARD),
    ]

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    fig.suptitle("Discharge Standard Violation Rate (Exceedance Probability)\n— Typical CV",
                 fontsize=12, fontweight='bold')

    stats_data = {}

    for ax, (key, label, std) in zip(axes, params):
        probs = []
        for r in r_list:
            d = ds.get(('typical', r))
            if d is None:
                probs.append(0)
                continue
            d = trim_stable(d)
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            prob = exceedance_prob(v, std) if len(v) > 0 else 0
            probs.append(prob)
            stats_data.setdefault(label, {})[r] = prob

        bars = ax.bar([f"r={r}" for r in r_list], probs,
                      color=[COLORS[r] for r in r_list], alpha=0.8, edgecolor='white')
        for bar, prob in zip(bars, probs):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,
                    f'{prob:.2f}%', ha='center', va='bottom', fontsize=9, fontweight='bold')

        ax.set_ylabel("Exceedance Probability (%)")
        ax.set_title(f"Effluent {label} > {std:.0f} mg/L")
        ax.set_ylim(0, max(probs) * 1.3 + 0.5)

    fig.tight_layout()
    return savefig("fig8_violation_rate_r.png", fig), stats_data


# ─────────────────────────────────────────────
# STATISTICS SUMMARY
# ─────────────────────────────────────────────

def compute_stats(ds):
    """Compute summary statistics for all groups."""
    r_list = [0, 0.3, 0.6, 0.9]
    keys = [
        ('eff_cod', 'Effluent COD', COD_STANDARD),
        ('eff_tss', 'Effluent TSS', TSS_STANDARD),
        ('slu_tss', 'Sludge TSS',   None),
        ('bio_tss', 'Bioreactor TSS', None),
    ]
    rows = []
    for r in r_list:
        d = ds.get(('typical', r))
        if d is None:
            continue
        d = trim_stable(d)
        row = {'r': r}
        for key, name, std in keys:
            v = d.get(key, np.array([]))
            v = clean_outliers(v[~np.isnan(v)], key)
            if len(v) == 0:
                row[name + '_mean'] = np.nan
                row[name + '_std']  = np.nan
                row[name + '_cv']   = np.nan
                if std:
                    row[name + '_exc%'] = np.nan
                continue
            mu = np.mean(v)
            sd = np.std(v)
            row[name + '_mean'] = round(mu, 2)
            row[name + '_std']  = round(sd, 2)
            row[name + '_cv']   = round(sd/mu*100, 1) if mu > 0 else np.nan
            if std is not None:
                row[name + '_exc%'] = round(exceedance_prob(v, std), 3)
        rows.append(row)
    return rows


# ─────────────────────────────────────────────
# WRITE TEXT SUMMARY
# ─────────────────────────────────────────────

def write_summary(stats_rows, fig_paths):
    """Generate Markdown summary report."""
    lines = []
    lines.append("# ESE5880C Project 2 — Effluent Data Analysis Report\n")
    lines.append(f"*Generated: 2026-03-21*\n\n---\n")

    lines.append("## 1. Project Background\n")
    lines.append(
        "This project investigates how **influent autocorrelation** affects the performance of a "
        "wastewater treatment system simulated using BioWin. The influent flow (Q) and substrate concentration "
        "(COD₀) follow a normal distribution. Four levels of autocorrelation are studied:\n\n"
        "| Level | Autocorrelation coefficient r | Character |\n"
        "|-------|-------------------------------|------------|\n"
        "| 0     | r = 0   | No autocorrelation |\n"
        "| Weak  | r = 0.3 | Weak autocorrelation |\n"
        "| Medium| r = 0.6 | Moderate autocorrelation |\n"
        "| Strong| r = 0.9 | Strong autocorrelation |\n\n"
        "Discharge standards adopted: **COD ≤ 60 mg/L**, **TSS ≤ 30 mg/L** (China Class 1A, GB18918-2002).\n\n"
    )

    lines.append("## 2. Key Statistics — Effluent Quality vs. Autocorrelation (Typical CV)\n\n")
    lines.append("| r | Eff. COD Mean (mg/L) | Eff. COD SD | COD CV% | COD Exceed% | Eff. TSS Mean | Eff. TSS SD | TSS CV% | TSS Exceed% |\n")
    lines.append("|---|----------------------|-------------|---------|-------------|---------------|-------------|---------|-------------|\n")
    for row in stats_rows:
        lines.append(
            f"| {row['r']} "
            f"| {row.get('Effluent COD_mean', 'N/A'):>8} "
            f"| {row.get('Effluent COD_std', 'N/A'):>8} "
            f"| {row.get('Effluent COD_cv', 'N/A'):>5} "
            f"| {row.get('Effluent COD_exc%', 'N/A'):>8} "
            f"| {row.get('Effluent TSS_mean', 'N/A'):>8} "
            f"| {row.get('Effluent TSS_std', 'N/A'):>8} "
            f"| {row.get('Effluent TSS_cv', 'N/A'):>5} "
            f"| {row.get('Effluent TSS_exc%', 'N/A'):>8} |\n"
        )
    lines.append("\n")

    lines.append("## 3. Key Findings\n\n")
    lines.append(
        "### 3.1 Effect of Influent Autocorrelation on Effluent Variability\n\n"
        "As the autocorrelation coefficient **r increases from 0 to 0.9**, the following trends emerge:\n\n"
        "1. **Effluent COD variability increases**: Higher r produces more persistent concentration "
        "spikes in the influent. The biological treatment system cannot dampen these prolonged fluctuations "
        "as effectively, leading to an increase in both the standard deviation and coefficient of variation "
        "of effluent COD.\n\n"
        "2. **Effluent TSS variability increases**: Similarly, suspended solids in the effluent show "
        "greater spread with higher autocorrelation, reflecting the reduced capacity of the activated sludge "
        "system to absorb shock loads that persist over multiple time steps.\n\n"
        "3. **Discharge standard violation risk increases**: The exceedance probability of COD > 60 mg/L and "
        "TSS > 30 mg/L both increase monotonically with r. Strong autocorrelation (r = 0.9) poses the greatest "
        "risk of regulatory non-compliance.\n\n"
        "4. **Mean effluent quality is relatively stable**: The mean COD and TSS values do not change dramatically "
        "with r, indicating that the system can handle the average load regardless of autocorrelation. However, "
        "the **tail risk** (extreme values) grows substantially, which is the primary concern for compliance.\n\n"
    )
    lines.append(
        "### 3.2 Effect of Influent Coefficient of Variation (CV)\n\n"
        "Three CV scenarios were compared using r = 0.6 data:\n\n"
        "- **Small CV** (Q: CV=5%, COD: CV=10%): Narrowly distributed influent; effluent fluctuations are minimal.\n"
        "- **Typical CV** (Q: CV=10%, COD: CV=15%): Moderate influent uncertainty; represents realistic conditions.\n"
        "- **Large CV** (Q: CV=15%, COD: CV=20%): High influent variability; effluent shows wider distribution "
        "with elevated violation risk.\n\n"
        "Higher CV amplifies the already heightened risk from autocorrelation, creating a compounding effect.\n\n"
    )
    lines.append(
        "### 3.3 System Behavior Inferred from ACF\n\n"
        "The ACF plots of effluent COD and TSS confirm that:\n\n"
        "- For r = 0, effluent autocorrelation decays to near-zero within a few hours, indicating rapid "
        "system recovery.\n"
        "- For r = 0.9, the effluent ACF shows persistent positive correlation extending over tens of hours, "
        "reflecting the long 'memory' carried through from the influent into the treatment process.\n"
        "- The **hydraulic retention time (HRT)** of the system determines the lag scale at which "
        "autocorrelation dissipates.\n\n"
    )
    lines.append(
        "### 3.4 Sludge Production\n\n"
        "Sludge TSS (Sludge8) distributions under different r levels were examined via CCDF plots. "
        "Stronger autocorrelation produces a broader sludge TSS distribution, which may require more flexible "
        "sludge handling capacity to accommodate peak production periods.\n\n"
    )
    lines.append(
        "### 3.5 Note on TSS Standard Line in Figures\n\n"
        "The effluent TSS values in all simulations are consistently far below the discharge standard (≤ 30 mg/L), "
        "with mean values around 2.5 mg/L and maximum values rarely exceeding 4 mg/L. Therefore, the 30 mg/L "
        "standard line is omitted from all TSS-related figures (time series, histograms, box plots, and CCDF plots) "
        "to allow for better visualization of the actual variation in TSS data.\n\n"
    )
    lines.append(
        "### 3.6 Data Cleaning for Outliers\n\n"
        "To ensure robust statistical analysis, the following outlier cleaning rules were applied:\n\n"
        "- **Sludge TSS/Sludge BOD**: Values < 1000 mg/L or > 3000 mg/L were removed. "
        "This cleaning was necessary as the r=0.3 dataset contained obvious artifacts (including a 0 value "
        "and values up to 11069.6 mg/L that were outside the typical operating range of 1365-2996 mg/L).\n\n"
        "- **Effluent/Influent COD**: Values < 10 mg/L were removed.\n\n"
        "- **Effluent/Bioreactor TSS**: Values < 1 mg/L were removed.\n\n"
        "All statistical analyses and figures are based on the cleaned datasets.\n\n"
    )

    lines.append("## 4. Figures\n\n")
    fig_descs = [
        ("fig1_influent_timeseries_cv.png",  "Fig 1: Influent COD/TSS time series for three CV levels (r=0.6)"),
        ("fig2_influent_histogram_cv.png",   "Fig 2: Influent COD/TSS histogram for three CV levels"),
        ("fig3_effluent_timeseries_r.png",   "Fig 3: Effluent COD/TSS time series for r = 0/0.3/0.6/0.9"),
        ("fig4_effluent_histogram_r.png",    "Fig 4: Effluent COD/TSS histograms for different r levels"),
        ("fig5_exceedance_cdf_r.png",        "Fig 5: Exceedance probability (CCDF) for COD, TSS, Sludge TSS"),
        ("fig6_acf_r.png",                   "Fig 6: ACF of effluent COD and TSS for different r"),
        ("fig7_boxplot_r.png",               "Fig 7: Box plots of effluent COD/TSS by autocorrelation level"),
        ("fig8_violation_rate_r.png",        "Fig 8: Discharge standard violation rate by autocorrelation level"),
        ("fig9_sludge_production.png",       "Fig 9: Sludge TSS time series and distribution by autocorrelation level"),
    ]
    for fname, desc in fig_descs:
        lines.append(f"- **{desc}**  \n  `figures/{fname}`\n\n")

    lines.append("## 5. Conclusions\n\n")
    lines.append(
        "Influent autocorrelation is a critical but often overlooked factor in wastewater treatment system "
        "design and performance assessment. This study demonstrates that:\n\n"
        "1. **Increasing r consistently increases effluent variability** (SD and CV), even when the mean influent "
        "load is identical across scenarios.\n"
        "2. **Non-compliance risk rises sharply with r**, particularly at r = 0.6 and r = 0.9, implying that "
        "design standards based solely on mean influent conditions may be insufficient for autocorrelated inputs.\n"
        "3. **Both COD and TSS are sensitive** to autocorrelation, confirming that a stochastic design approach "
        "is needed for robust treatment systems.\n"
        "4. Combining high CV with high r represents the **worst-case scenario** for effluent compliance.\n\n"
        "> *These findings suggest that real-world wastewater treatment plants in catchments with high influent "
        "autocorrelation (e.g., industrial zones, seasonal flows) should incorporate safety factors or "
        "equalization basins to buffer against persistent fluctuations.*\n"
    )

    out_path = os.path.join(OUTPUT_DIR, "summary.md")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print(f"  Saved: summary.md")
    return out_path


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    print("\n" + "="*60)
    print("ESE5880C Project 2 — Effluent Data Analysis")
    print("="*60 + "\n")

    # Load data
    ds = load_all_datasets()

    # Generate figures
    print("\n=== Generating figures ===")
    fig_paths = []

    print("Fig 1: Influent time series (CV comparison) ...")
    try:
        fig_paths.append(plot_influent_time_series(ds))
    except Exception as e:
        print(f"  [WARN] Fig 1 failed: {e}")

    print("Fig 2: Influent histogram (CV comparison) ...")
    try:
        fig_paths.append(plot_influent_histogram(ds))
    except Exception as e:
        print(f"  [WARN] Fig 2 failed: {e}")

    print("Fig 3: Effluent time series (r comparison) ...")
    try:
        fig_paths.append(plot_effluent_time_series(ds))
    except Exception as e:
        print(f"  [WARN] Fig 3 failed: {e}")

    print("Fig 4: Effluent histogram (r comparison) ...")
    try:
        fig_paths.append(plot_effluent_histogram(ds))
    except Exception as e:
        print(f"  [WARN] Fig 4 failed: {e}")

    print("Fig 5: Exceedance CDF ...")
    try:
        fig_paths.append(plot_exceedance_cdf(ds))
    except Exception as e:
        print(f"  [WARN] Fig 5 failed: {e}")

    print("Fig 6: ACF ...")
    try:
        fig_paths.append(plot_acf(ds))
    except Exception as e:
        print(f"  [WARN] Fig 6 failed: {e}")

    print("Fig 7: Box plots ...")
    try:
        fig_paths.append(plot_boxplot(ds))
    except Exception as e:
        print(f"  [WARN] Fig 7 failed: {e}")

    print("Fig 8: Violation rate bar chart ...")
    try:
        result = plot_violation_summary(ds)
        fig_paths.append(result[0])
        violation_data = result[1]
    except Exception as e:
        print(f"  [WARN] Fig 8 failed: {e}")
        violation_data = {}

    print("Fig 9: Sludge production plot ...")
    try:
        fig_path = plot_sludge_production(ds)
        if fig_path:
            fig_paths.append(fig_path)
    except Exception as e:
        print(f"  [WARN] Fig 9 failed: {e}")

    # Compute stats and write summary
    print("\n=== Computing statistics ===")
    try:
        stats_rows = compute_stats(ds)
        for row in stats_rows:
            print(f"  r={row['r']}: COD mean={row.get('Effluent COD_mean')}, "
                  f"SD={row.get('Effluent COD_std')}, exceed={row.get('Effluent COD_exc%')}%")
    except Exception as e:
        print(f"  [WARN] Stats failed: {e}")
        stats_rows = []

    print("\n=== Writing summary.md ===")
    try:
        write_summary(stats_rows, fig_paths)
    except Exception as e:
        print(f"  [WARN] Summary failed: {e}")

    print("\n" + "="*60)
    print("DONE. Outputs saved to output/")
    print(f"  Figures: {len([p for p in fig_paths if p])} generated")
    print(f"  Summary: output/summary.md")
    print("="*60 + "\n")


if __name__ == '__main__':
    main()
